server:
  port: 9090

---
spring:
  config:
    activate:
      on-profile: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://ac9d448751edc4aee94e5b252558f421-1054032099.us-east-1.elb.amazonaws.com
